name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Allow build
      run: chown -R $(id -un):$(id -gn) ~
    
    - name: Build with Stack
      run: stack build --allow-different-user

    - name: Test with Stack
      run: stack test --allow-different-user
