name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.4.7'
        cabal-version: '3.2'
        enable-stack: true
        stack-version: 'latest'
    
    - name: Build with Stack
      run: stack build

    - name: Test with Stack
      run: stack test
