name: Build and test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fase: false
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v4

    - run: |
        stack build --allow-different-user
        stack test --allow-different-user

    - uses: actions/upload-artifact@v3
      with:
        name: glados
        path: glados
        if-no-files-found: error
