name: Build and test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        chown -R $(id -un):$(id -gn) "$HOME"
        make STACK='stack --allow-different-user'

    - name: Upload bin
      uses: actions/upload-artifact@v3
      with:
        name: glados
        path: glados
        if-no-files-found: error

  test:
    container: epitechcontent/epitest-docker:latest

    - run: make STACK='stack --allow-different-user' test
