name: Build and test

on: push

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and test
      run: |
        chown -R $(id -un):$(id -gn) "$HOME"
        make STACK='stack --allow-different-user'
        make STACK='stack --allow-different-user' test

    - uses: actions/upload-artifact@v3
      with:
        path: glados

  release:
    runs-on: ubuntu-latest

    steps:
    - name: actions/download-artifact@v3
      with:
        path: glados

    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: glados
