name: Build and test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        chown -R $(id -un):$(id -gn) "$HOME"
        make

    - name: Test
      run: make test

    - name: Upload bin
      uses: actions/upload-artifact@v3
      with:
        name: glados
        path: glados
        if-no-files-found: error
