name: Build and test

on: push

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        chown -R $(id -un):$(id -gn) "$HOME"
        make STACK='stack --allow-different-user'

    - name: Test
      run: make STACK='stack --allow-different-user' test

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        repo_token: ${{ github.token }}
        files: glados
        prerelease: false
        automatic_release_tag: true
