name: Haskell CI

on: [push]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-FUN-500-TLS-5-1-glados-quentin.challon.git

jobs:
  build:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Allow build
      run: chown -R $(id -un):$(id -gn) ~
    
    - name: Build with Stack
      run: stack build --allow-different-user

    - name: Test with Stack
      run: stack test --allow-different-user

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Release v.0.${{ github.run_number }}

  pushing_to_the_mirror_repo:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Mirror repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ env.MIRROR_URL }}
        ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
