name: Mirror

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-FUN-500-TLS-5-1-glados-quentin.challon.git

on: push

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Mirror repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ env.MIRROR_URL }}
        ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
